/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyPackage;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.text.SimpleDateFormat;
import java.util.Date;
import MyPackage.Clients;
import MyPackage.Virement;
import MyPackage.Preter;
import MyPackage.Rendre;
import javax.swing.JInternalFrame;
/**
 *
 * @author Mandranto
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    

    public Main() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPaneMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonMainClients = new javax.swing.JButton();
        jButtonMainVirements = new javax.swing.JButton();
        jButtonRendre = new javax.swing.JButton();
        jButtonPrets = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jDesktopPaneMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jDesktopPaneMainLayout = new javax.swing.GroupLayout(jDesktopPaneMain);
        jDesktopPaneMain.setLayout(jDesktopPaneMainLayout);
        jDesktopPaneMainLayout.setHorizontalGroup(
            jDesktopPaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );
        jDesktopPaneMainLayout.setVerticalGroup(
            jDesktopPaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(jDesktopPaneMain, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jDesktopPaneMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jDesktopPaneMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 650, 520));

        jButtonMainClients.setText("CLIENTS");
        jButtonMainClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMainClientsActionPerformed(evt);
            }
        });

        jButtonMainVirements.setText("VIREMENTS");
        jButtonMainVirements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMainVirementsActionPerformed(evt);
            }
        });

        jButtonRendre.setText("RENDRE");
        jButtonRendre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRendreActionPerformed(evt);
            }
        });

        jButtonPrets.setText("PRETS");
        jButtonPrets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButtonMainClients, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jButtonMainVirements, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jButtonPrets, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jButtonRendre, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMainClients, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMainVirements, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRendre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPrets, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 780, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMainVirementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMainVirementsActionPerformed
    this.jDesktopPaneMain.removeAll();
    this.jDesktopPaneMain.repaint();
    Virement virement = new Virement();
    JInternalFrame internalFrame = new JInternalFrame("Virement", false, false, false, false);
    internalFrame.setContentPane(virement.getContentPane());
    internalFrame.setSize(virement.getSize());

    // Empêcher le cadre interne de se déplacer
    internalFrame.setLocation(internalFrame.getX(), internalFrame.getY());

    internalFrame.setVisible(true);
    jDesktopPaneMain.add(internalFrame);

    }//GEN-LAST:event_jButtonMainVirementsActionPerformed

    private void jButtonMainClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMainClientsActionPerformed
       this.jDesktopPaneMain.removeAll();
    this.jDesktopPaneMain.repaint();
    Clients clients = new Clients();
    JInternalFrame internalFrame = new JInternalFrame("CLIENTS", false, false, false, false);
    internalFrame.setContentPane(clients.getContentPane());
    internalFrame.setSize(clients.getSize());

    // Empêcher le cadre interne de se déplacer
    internalFrame.setLocation(internalFrame.getX(), internalFrame.getY());

    internalFrame.setVisible(true);
    jDesktopPaneMain.add(internalFrame);

    }//GEN-LAST:event_jButtonMainClientsActionPerformed

    private void jButtonPretsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretsActionPerformed
       this.jDesktopPaneMain.removeAll();
    this.jDesktopPaneMain.repaint();
    Preter preter = new Preter();
    JInternalFrame internalFrame = new JInternalFrame("Preter", false, false, false, false);
    internalFrame.setContentPane(preter.getContentPane());
    internalFrame.setSize(preter.getSize());

    // Empêcher le cadre interne de se déplacer
    internalFrame.setLocation(internalFrame.getX(), internalFrame.getY());

    internalFrame.setVisible(true);
    jDesktopPaneMain.add(internalFrame);
    }//GEN-LAST:event_jButtonPretsActionPerformed

    private void jButtonRendreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRendreActionPerformed
       this.jDesktopPaneMain.removeAll();
    this.jDesktopPaneMain.repaint();
    Rendre rendre = new Rendre();
    JInternalFrame internalFrame = new JInternalFrame("Rendre", false, false, false, false);
    internalFrame.setContentPane(rendre.getContentPane());
    internalFrame.setSize(rendre.getSize());

    // Empêcher le cadre interne de se déplacer
    internalFrame.setLocation(internalFrame.getX(), internalFrame.getY());

    internalFrame.setVisible(true);
    jDesktopPaneMain.add(internalFrame);
    }//GEN-LAST:event_jButtonRendreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMainClients;
    private javax.swing.JButton jButtonMainVirements;
    private javax.swing.JButton jButtonPrets;
    private javax.swing.JButton jButtonRendre;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jDesktopPaneMain;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
