/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyPackage;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
/**
 *
 * @author Mandranto
 */
public class Rendre extends javax.swing.JFrame {

    private static final String username = "root" ;
    private static final String password = "" ;
    private static final String dataConn = "jdbc:mysql://localhost:3306/banque" ;
    
    Connection sqlConn = null ;
    PreparedStatement pst = null ;
    PreparedStatement pst2 = null ;
    PreparedStatement pst3 = null ;
    ResultSet rs = null;
    int q, i, id, deleteItem;
    public Rendre() {
        initComponents();
        Read();
        UpdatejComboBoxNumPret();
        jButtonModifierRendre.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void UpdatejComboBoxNumPret() {
    String request = "SELECT * FROM preter";
    try {
        Class.forName("com.mysql.jdbc.Driver");
        sqlConn = DriverManager.getConnection(dataConn, username, password);
        pst = sqlConn.prepareStatement(request);
        rs = pst.executeQuery();
        
        jComboBoxNuméroDuPret.removeAllItems(); // Supprime tous les éléments précédents
        while(rs.next()) {
            jComboBoxNuméroDuPret.addItem(rs.getString("num_pret")); // Ajoute les nouveaux éléments
        }
        
        // Fermez la connexion, l'instruction préparée et le résultat
        //rs.close();
        //pst.close();
        //sqlConn.close();
    } catch(ClassNotFoundException | SQLException e) {
        JOptionPane.showMessageDialog(null, e);
    }
}

    public void Read() {
    try {
        Class.forName("com.mysql.jdbc.Driver");
        sqlConn = DriverManager.getConnection(dataConn, username, password);
        pst = sqlConn.prepareStatement("SELECT * FROM rendre");

        rs = pst.executeQuery();
        ResultSetMetaData rsMetaData = rs.getMetaData();

        int columnCount = rsMetaData.getColumnCount();
        DefaultTableModel recordTable = (DefaultTableModel) jTableRendre.getModel();
        recordTable.setRowCount(0);

        while (rs.next()) {
            Vector<Object> rowData = new Vector<>();

            for (int i = 1; i <= columnCount; i++) {
                rowData.add(rs.getObject(i));
            }

            recordTable.addRow(rowData);
        }
    } catch (ClassNotFoundException | SQLException ex) {
        JOptionPane.showMessageDialog(null, ex);
    }
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelNuméroRendre = new javax.swing.JLabel();
        jLabelNuméroDuPretRendre = new javax.swing.JLabel();
        jTextNuméroRendre = new javax.swing.JTextField();
        jLabelDateRendue = new javax.swing.JLabel();
        jTextDateRendue = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRendre = new javax.swing.JTable();
        jButtonAjouterRendre = new javax.swing.JButton();
        jButtonModifierRendre = new javax.swing.JButton();
        jButtonSupprimerRendre = new javax.swing.JButton();
        jComboBoxNuméroDuPret = new javax.swing.JComboBox<>();
        jLabelMontantPayer = new javax.swing.JLabel();
        jTextMontantPayer = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNuméroRendre.setText("Numéro Rendre");

        jLabelNuméroDuPretRendre.setText("Numéro du Pret");

        jTextNuméroRendre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNuméroRendreActionPerformed(evt);
            }
        });

        jLabelDateRendue.setText("Date Rendue");

        jTextDateRendue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDateRendueActionPerformed(evt);
            }
        });

        jTableRendre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numéro Rendre", "Numéro du Pret", "Situation", "Date Rendue"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableRendre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRendreMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableRendreMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableRendre);

        jButtonAjouterRendre.setText("Effectuer Rendre");
        jButtonAjouterRendre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterRendreActionPerformed(evt);
            }
        });

        jButtonModifierRendre.setText("Modifier");
        jButtonModifierRendre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierRendreActionPerformed(evt);
            }
        });

        jButtonSupprimerRendre.setText("Supprimer");
        jButtonSupprimerRendre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerRendreActionPerformed(evt);
            }
        });

        jLabelMontantPayer.setText("Montant à payer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelMontantPayer, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jTextMontantPayer))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNuméroDuPretRendre, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNuméroRendre, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextNuméroRendre)
                            .addComponent(jComboBoxNuméroDuPret, 0, 207, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelDateRendue, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextDateRendue, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonModifierRendre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAjouterRendre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSupprimerRendre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(87, 87, 87))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNuméroRendre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNuméroRendre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAjouterRendre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNuméroDuPretRendre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxNuméroDuPret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModifierRendre, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSupprimerRendre)
                    .addComponent(jLabelDateRendue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDateRendue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMontantPayer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextMontantPayer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNuméroRendreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNuméroRendreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNuméroRendreActionPerformed

    private void jButtonAjouterRendreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterRendreActionPerformed
       try {
        Class.forName("com.mysql.jdbc.Driver");
        sqlConn = DriverManager.getConnection(dataConn, username, password);
        sqlConn.setAutoCommit(false); // Commencer une transaction

        // Préparer les requêtes préparées
        pst = sqlConn.prepareStatement("INSERT INTO rendre (num_rendu, num_pret, situation, date_rendu, rest_payé) VALUES (?, ?, ?, ?, ?)");
        pst2 = sqlConn.prepareStatement("UPDATE rendre SET rest_payé = rest_payé - ? WHERE num_pret = ?");
        pst3 = sqlConn.prepareStatement("SELECT montant_preté, rest_payé FROM preter WHERE num_pret = ?");

        // Récupérer les valeurs des champs
        String numRendre = jTextNuméroRendre.getText();
        String numPret = jComboBoxNuméroDuPret.getSelectedItem().toString();
        String dateRendue = jTextDateRendue.getText();
        int restePayer = Integer.parseInt(jTextMontantPayer.getText());

        // Obtenir le montant prêté et le montant restant à payer de la table "preter"
        int montantPret = 0;
        int montantRestant = 0;
        pst3.setString(1, numPret);
        ResultSet rs = pst3.executeQuery();
        if (rs.next()) {
            montantPret = rs.getInt("montant_preté");
            montantRestant = rs.getInt("rest_payé");
        }

        String situation;
        if (restePayer < montantPret) {
            situation = "Payé à part";
            montantRestant -= restePayer;
        } else {
            situation = "Tout Payer";
            montantRestant = 0;
        }

        // Définir les paramètres pour les requêtes préparées
        pst.setString(1, numRendre);
        pst.setString(2, numPret);
        pst.setString(3, situation);
        pst.setString(4, dateRendue);
        pst.setInt(5, restePayer);

        pst2.setInt(1, restePayer);
        pst2.setString(2, numPret);

        // Exécuter les requêtes préparées
        pst.executeUpdate();
        pst2.executeUpdate();

        // Mettre à jour le montant restant à payer dans la table "preter"
        PreparedStatement pst4 = sqlConn.prepareStatement("UPDATE preter SET rest_payé = ? WHERE num_pret = ?");
        pst4.setInt(1, montantRestant);
        pst4.setString(2, numPret);
        pst4.executeUpdate();

        sqlConn.commit(); // Valider la transaction

        JOptionPane.showMessageDialog(this, "Rendu effectué avec succès !");

        // Effacer les champs de saisie
        jTextNuméroRendre.setText("");
        jTextDateRendue.setText("");
        jTextMontantPayer.setText("");

        // Mettre à jour le tableau des rendus
        Read();
    } catch (ClassNotFoundException | SQLException ex) {
        // En cas d'erreur, annuler la transaction
        if (sqlConn != null) {
            try {
                sqlConn.rollback();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

        JOptionPane.showMessageDialog(null, ex);
    } finally {
        // Rétablir le mode de validation automatique et fermer la connexion
        if (sqlConn != null) {
            try {
                sqlConn.setAutoCommit(true);
                sqlConn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    }//GEN-LAST:event_jButtonAjouterRendreActionPerformed

    private void jButtonModifierRendreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierRendreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModifierRendreActionPerformed

    private void jButtonSupprimerRendreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerRendreActionPerformed
       try
        {
            //id  = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());//tsy ilaina
            deleteItem = JOptionPane.showConfirmDialog(null, "Confirm if you wanna delete","warning",JOptionPane.YES_NO_OPTION);
            if(deleteItem == JOptionPane.YES_OPTION)
            {
                Class.forName("com.mysql.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataConn,username,password);
                pst = sqlConn.prepareStatement("DELETE FROM rendre WHERE num_rendu = ? ");
              
              pst.setString(1, jTextNuméroRendre.getText());
                
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Deleted");
                Read();
                jTextNuméroRendre.setText("");
                jTextDateRendue.setText("");
                jTextMontantPayer.setText("");
            }
        }
        catch(ClassNotFoundException ex)
         {
             java.util.logging.Logger.getLogger(Preter.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
         }
         catch(SQLException ex)
         {
            System.err.println(ex);
         }
    }//GEN-LAST:event_jButtonSupprimerRendreActionPerformed

    private void jTextDateRendueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDateRendueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDateRendueActionPerformed

    private void jTableRendreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRendreMouseClicked
               DefaultTableModel recordTable = (DefaultTableModel) jTableRendre.getModel();
int selectedRow = jTableRendre.getSelectedRow();
jTextNuméroRendre.setText(recordTable.getValueAt(selectedRow, 0).toString());
jComboBoxNuméroDuPret.setSelectedItem(recordTable.getValueAt(selectedRow, 1).toString());
jTextDateRendue.setText(recordTable.getValueAt(selectedRow, 3).toString());


//jTextMontantPayer.setText(recordTable.getValueAt(selectedRow, 4).toString());

    }//GEN-LAST:event_jTableRendreMouseClicked

    private void jTableRendreMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRendreMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableRendreMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rendre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rendre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rendre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rendre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rendre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAjouterRendre;
    private javax.swing.JButton jButtonModifierRendre;
    private javax.swing.JButton jButtonSupprimerRendre;
    private javax.swing.JComboBox<String> jComboBoxNuméroDuPret;
    private javax.swing.JLabel jLabelDateRendue;
    private javax.swing.JLabel jLabelMontantPayer;
    private javax.swing.JLabel jLabelNuméroDuPretRendre;
    private javax.swing.JLabel jLabelNuméroRendre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRendre;
    private javax.swing.JTextField jTextDateRendue;
    private javax.swing.JTextField jTextMontantPayer;
    private javax.swing.JTextField jTextNuméroRendre;
    // End of variables declaration//GEN-END:variables
}
